### ISSUE TITLE
v0.3.1 & v0.3.0: second time tester powers up with "Bye!" message and won't turn off

### ISSUE THREAD

**Issue by ejouellette** [atar-axis/tc1-u4#4]
Thank you for providing custom firmware for the timer chip! It's great for us hobbyists who want to run the latest firmware from Markus and Karl-Heinz.

I have an LCR-TC2 tester with ST15W104 timer chip.
After programming it with v0.3.1 or v0.3.0 timer chip firmware, initially the tester seems to work ok.
Pressing the button wakes up the tester, the firmware version (1.47m) is displayed, and it repeatedly probes and displays the installed component until the button is held in. Then it briefly flashes "Bye!" and turns off. 
The next time the button is pressed with no component installed, the unit wakes up again, but immediately goes to "Bye!" message (skipping firmware version), and does not shut down. Additional button presses have no effect at this time; the only way to reset the tester is to remove the battery, wait a few seconds, then reinstall it.
Also, selecting the "Off" menu option turns of the tester with "Bye!" message, however, the next time the button is pressed the same problem happens as outlined above.
There seems to be a timing issue(s). Maybe the button is not being debounced properly?
Would you please help? Thanks!

**Comment by atar-axis** [comment]
Absolutely possible, there is even a comment about denouncing not working efficiently in the code. But since it is 4 years since I did sth here I can't remember tbh.

Should be easy to change. Give it a try - PRs are welcome :)

**Comment by ejouellette** [comment]
Thanks for your fast reply. I'll take a look. 
Which IDE did you use, and where can I download a version which works for the project?
Thanks!

**Comment by atar-axis** [comment]
Can't tell you much more than what I've documented in the readme. I think that should be sufficient though :)

**Comment by ejouellette** [comment]
Sorry, I should have read the readme... I found the info. thanks!

**Comment by ejouellette** [comment]
I just submitted a pull request. The source code was very clean and easy to read. It made debugging much easier, thanks!
The state machine implementation is very cool.
I was able to improve the timing and efficiency with a different debounce method for the button and stay with the Moore machine implementation. I've tested successfully on an LCR-TC2 unit. Please let me know if you have any questions.
Hope this helps!

**Comment by atar-axis** [comment]
Thank you very much! Great that you took the time to improve it, very cool. I just merged it. :)

**Comment by 2Torr** [comment]
Great, thanks!

**Comment by ejouellette** [comment]
Great, thanks!

**Comment by atar-axis** [comment]
I like the shift register thingy! Nice one :)

**Comment by ejouellette** [comment]
Thanks, I copied the idea from an article on debouncing from the Ganssle group, You may find it an interesting rainy day read:
http://www.ganssle.com/debouncing.htm

**Comment by atar-axis** [comment]
Interesting article! Thanks for sharing :)
